#!/usr/bin/perl

use strict;
use warnings;
use Proc::ProcessTable;

my $big;
my $buf='sssssss';

#usage: ./mem_test

for (1..17) {
for(1..100000000) {
$big.=$buf;
}
print "mem usage: ",&mem_use,"\n";
}
sleep;
sub mem_use {
	my $t=new Proc::ProcessTable;
	for my $got(@{$t->table}) {
		next if not $got->pid eq $$;
		my $mem=$got->size/1024;
		return "${mem}KB";
	}
}
