#!/usr/bin/env perl

use strict;
use warnings;

open IN,"<","/usr/share/dict/words" or die "\n";

my @a=<IN>;
chomp @a;
my $q="yunfei";

($q,@a)=map lc,($q,@a);
my $index=&bsearch(\@a,$q);
if (defined $index) #index could be 0, which refers to the 1st element
{
	warn "index: $index\n";
} else
{
	warn "Not found\n";
}

#search a word in alphabetically sorted list
sub bsearch
{
 my @array=@{shift @_};
 my $word=shift;
 my $low=0;
 my $hi=@array-1;

 while ($low<=$hi)
 {
 	my $try=int(0.5*($low+$hi));
	#print "$array[$try]    $word\n";
	if ($array[$try] lt $word)
	{
		$low=$try+1;
	} elsif ($array[$try] gt $word)
	{
		$hi=$try-1;
	} else
	{
		return $try;
	}
 }
 return undef;
}
