#!/usr/bin/env perl

use strict;
use warnings;

#input format (tab-delimited):
#3000	0 #total,0 place-holder 
#1000	10 #deposit or withdraw, days to today
#1500	5
#-300	3

#calculate compound annual growth rate
#formula x1(1+r)^t1+x2(1+r)^t2+...=total

die "Usage: $0 data.txt\n" unless @ARGV==1;

my $data=shift @ARGV;

open (my $IN,"<",$data) or die "Cannot open $data: $!\n";
my @all=<$IN>;
my $total=shift @all;
($total)= $total=~/([^\t]+)\t/;
my @term_list;
for (@all)
{
	my ($x,$t)=split;
	die "Second column must be nonnegative!\n" if $t<0;
	$t=$t/365;
	my $term="($x*(1+\$r)**$t)";
	push @term_list,$term;
}

my $max_iteration=1e3;
my $count=0;
my $threshold=1e-6;
my $r=0; #Support: [0,1]
my ($min,$max)=(0,1);
my $formula=join '+',@term_list;
while(1)
{
        my $result=eval($formula)-$total;
   	warn "Compound annual growth rate: $r\n" and exit if abs($result)<$threshold; 
	
	#dichotomy method
	if ($result>0)
	{
	    $max=$r;
	    $r=0.5*($min+$max);
	} elsif ($result<0)
	{
	    $min=$r;
	    $r=0.5*($min+$max);
	}

	$count++;
	die "Exceeds max number of iterations\n" if $count>$max_iteration;
}

