#!/usr/bin/env perl

use strict;
use warnings;

my $kid_pid=fork();
unless ($kid_pid)
{
    die "child died: $kid_pid";
    #sleep;
}

sleep 2;
print "pid: $kid_pid\n";
unless (kill 0 => $kid_pid)
{
	warn "child???";
}
