#!/usr/bin/env perl

use strict;
use warnings;

#extract reads from FASTQ files based on length

die "Usage: $0 <INT> file.fastq> output.fastq\n".
"Extract reads of INT bp from file.fastq\n" unless @ARGV==2;

my $len=shift @ARGV;
my $item=shift @ARGV;

die "$item not found\n" unless -f $item;
&sanity_check($item) or die "Not all reads have 4 lines\n";
open IN,'<',$item or die "Cannot open $item\n";
warn "Reading $item ...\n";
while(<IN>)
{
    if (/^@/)
    {
	my $base=<IN>;
	if (length($base)==$len+1) #one trailing newline
	{
	    print $_;
	    print $base;
	    $_=<IN>;
	    print $_;  #3rd line
	    $_=<IN>;
	    print $_;  #base quality
	} else #in case base quality begins with @
	{
	  $_=<IN>; #3rd line
	  $_=<IN>; #4th line
	}
    }
}

sub sanity_check
{
    my $file=shift;
    warn "Checking if all reads have 4 lines\n";
    my $line_count=`wc -l $file`;
    $line_count=~s/^(\d+)\s.*/$1/;
    return	($line_count % 4 ? 0 : 1);
}
