#!/usr/bin/env perl

use strict;
use warnings;
use Benchmark qw/timethese/;

timethese(99999,{
'recursive' => '&recur(10)',
'dynamic'   => '&dynam(10)',
});

sub recur
{
    my $n=shift;
    return unless $n>=0;

    if ($n == 0)
    {
	return 0;
    } elsif ($n == 1)
    {
	return 1;
    } else
    {
	return (&recur($n-1)+&recur($n-2));
    }
}

sub dynam
{
    my $n=shift;
    my %tmp;
    return unless $n>=0;

    $tmp{1}=1;
    $tmp{0}=0;
    if ($n>1)
    {
	for (2..$n)
	{
	    $tmp{$_}=$tmp{$_-1}+$tmp{$_-2};
	}
    }
    return $tmp{$n};
}
