#!/usr/bin/env perl

use strict;
use warnings;

die "Usage: $0 <DNA seq>\n" unless @ARGV==1;
my $seq=shift @ARGV;
warn "Output reversed complimentary sequence:\n";
print &revCom($seq),"\n";
sub revCom
{
	my $in=shift;
	my @out;
	for (split //,$in)
	{
		$_=~tr/atcgATCG/tagcTAGC/;
		push @out,$_;
	}
	return join('',reverse @out);
}
