#!/usr/bin/env perl

use strict;
use warnings;

die "Usage: $0 tower1 tower2 tower3 n\n" unless @ARGV==4;
my $total=0;

&next(@ARGV);

sub next
{
	#usage: &next("t1","t2","t3",$n);
	#print out solution recursively
	my ($start,$spare,$end,$n)=@_;
	$n=int(abs($n));
	if ($n == 1)
	{
		$total++;
		print "$start->$end: $total\n";
	} else
	{
		&next($start,$end,$spare,$n-1);
		$total++;
		print "$start->$end: $total\n";
		&next($spare,$start,$end,$n-1);
	}

}
