#!/usr/bin/env perl

use strict;
use warnings;

my $s=<<END;
This a 
LARGE
block of text.
END

print $s;

#interpolation
my $s1=<<END;
Do you see $s?
END

print $s1;

#no interpolation
my $s1=<<'END';
Do you see $s?
END

print $s1;
