#!/usr/bin/env perl

use strict;
use warnings;
use Memoize;

sub calc_big
{
	my $q=0;
	my $n=shift;
	for (1..$n)
	{
		$q=1/(1+$q);
	}
	return $q;
}

#memoize 'calc_big';
print &calc_big(10000000);
warn "BLANK\n";
print &calc_big(10000000);
print &calc_big(10000000);
