#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename qw/basename/;

#number of parts after split
die "Usage: $0 <INT number of parts> <1.file 2.file ...>\n" unless @ARGV>=2;
my $N=shift @ARGV;
die "Integer expected: $N\n" if $N=~/\D/;

for my $i(@ARGV)
{
    my $prefix = basename $i;
    my $suffix;
    ($prefix,$suffix) = $prefix=~/^(.*?)\.([^.]+)$/;
    $prefix .= ".";
    warn "NOTICE: splitting $i into $N parts by line count\n";
    my $wc = `wc -l $i`;
    chomp $wc;
    $wc =~ s/^(\d+).*/$1/g;
    die "Cannot split $i into $N parts\n" if($wc % $N != 0);

	my $new_wc = $wc/$N;
    !system("split --suffix-length=5 -d -l $new_wc $i $prefix") or die "Failed to split: $!\n";
}
