#!/usr/bin/perl

use strict;
use warnings;

setpgrp(0,0);

warn "Group leader PID: $$\n";

if (my $pid1=fork())
{
	1;
} else
{
	local $SIG{HUP}=sub {die "CHILD $$ killed"};
	sleep;
}

if (my $pid2=fork())
{
	1;
} else
{
	local $SIG{HUP}=sub {die "CHILD $$ killed"};
	sleep;
}

{
	local $SIG{HUP}="IGNORE"; #exempt myself
	kill('HUP',-$$);		  #signal my own process group
}
