#!/usr/bin/env perl

use strict;
use warnings;
use POSIX qw(:signal_h :errno_h :sys_wait_h);

$SIG{CHLD}=\&REAPER;
sub REAPER
{
	my $pid;
	$pid=waitpid(-1,WNOHANG);

	if ($pid == -1)
	{
		#no child waiting; ignore it
	} elsif (WIFEXITED($?))
	{
		print "Process $pid exited\n";
	} else 
	{	
		print "False alarm on $pid\n";
	}
	$SIG{CHLD}=\&REAPER;
}

if (my $pid=fork)
{
	print "parent\n";
	waitpid($pid,0);
} else
{
    for (my $i=1;$i++;99999)
    {
	exp($i);
    }
}
