#!/usr/bin/env perl

use strict;
use warnings;

my %op=(
	'+' => sub {$_[0] + $_[1]},
	'-' => sub {$_[0] - $_[1]},
	'*' => sub {$_[0] * $_[1]},
	'/' => sub {$_[0] / $_[1]},
);

my $a=1;
my $b=2;
print &{$op{'+'}}($a,$b),"\n";
print &{$op{'/'}}($a,$b),"\n";
