version: "3"
services:
    web:
        image: carlocreator/get-started:part2
        deploy:
            replicas: 50
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4000:80"
        networks:
            - webnet
networks:
    webnet:
