//
// Created by guoy28 on 1/13/17.
//

#ifndef THE_CPP_LANGUAGE_TUTORIAL_DYNAMICMEMORY_H
#define THE_CPP_LANGUAGE_TUTORIAL_DYNAMICMEMORY_H

#endif //THE_CPP_LANGUAGE_TUTORIAL_DYNAMICMEMORY_H
int dynamicMemory();
