//
// Created by guoy28 on 1/13/17.
//

#ifndef THE_CPP_LANGUAGE_TUTORIAL_STRINGSTREAM_H
#define THE_CPP_LANGUAGE_TUTORIAL_STRINGSTREAM_H

#endif //THE_CPP_LANGUAGE_TUTORIAL_STRINGSTREAM_H
int myStringstream();
