//
// Created by guoy28 on 1/13/17.
//

#ifndef THE_CPP_LANGUAGE_TUTORIAL_OVERLOADING_H
#define THE_CPP_LANGUAGE_TUTORIAL_OVERLOADING_H

#endif //THE_CPP_LANGUAGE_TUTORIAL_OVERLOADING_H
int overloading();
