#!/usr/bin/env python

def divide (x,y):
    try:
	result=x/y
    except ZeroDivisionError:
	print "Cannot divide 0!"
    else:
	print "result is "+str(result)
    finally:
	print "running finally clause"

if __name__ == "__main__":
    divide(1,1)
