#!/usr/bin/env python

def monthlyPayment (balance, apr, months):
 '''
 calculate fixed monthly payment in whole 10 dollars
 '''
 pay=0
 while True:
  newBalance=balance
  for i in range (months):
   unpaidBalance=newBalance-pay
   newBalance=unpaidBalance*(1+apr/12)
  if unpaidBalance <= 0:
   break
  pay=pay+0.01
 print ("Lowest payment: %s" % pay)

monthlyPayment(4773,0.2,12)

