#!/usr/bin/env python

def monthlyPayment (balance, apr, monthlyMinPayRate, months):
 totalPaid=0
 for i in range(months):
  minPay=balance*monthlyMinPayRate
  totalPaid=totalPaid+minPay
  unpaidBalance=balance-minPay
  balance=unpaidBalance*(1+apr/12)
  print ("Month: %s" % (i+1))
  print ("Minimum monthly payment: %s" % round(minPay,2))
  print ("Remaining balance: %s" % round(balance,2))
 print ("Total paid: %s" % round(totalPaid,2))
 print ("Remaining Balance: %s" % round(balance,2))

monthlyPayment(5000,0.18,0.02,12)

