#!/usr/bin/env python


class Coordinate():
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def kk(self,x):
    print x
  def dd(self,y):
    self.kk(y) 

if __name__=='__main__':
  c=Coordinate(10,1)
  c.dd(1)
