# User specific environment and startup programs

#universal PATH settings
export PATH=$HOME/bin:$PATH

#custom PATH settings

#LD_LIBRARY_PATH
#these settings for runtime library search path
#better solution is: compile with LD_FLAGS="-Wl,-rpath,/path/to/lib",
#so program knows where to search lib at runtime
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib

#bash settings
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
export JIRA_HOME=/Users/guoy28/Downloads/jira7_home
export HISTSIZE=5000000
export HISTFILESIZE=5000000
export GIT_SSL_NO_VERIFY=true
export PS1='[\A \u@\H \W]\$ '
export R_LIB=$HOME/.R
export MACHTYPE=x86_64
export EDITOR=vi
export HISTCONTROL=ignoredups
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"


#alias
alias hpcc='ssh yunfeigu@hpc-login2.usc.edu'
alias uec='ssh yunfeigu@hpc-uec.usc.edu'
alias bionas='ssh yunfeiguo@bionas.usc.edu'
alias bclold='ssh yunfeiguo@biocluster.med.usc.edu'
alias bcl='ssh yunfeiguo@biocluster.wglab.org'
alias h=history
alias bif="ssh yunfeiguo@bioinform.med.usc.edu"
alias bif2="ssh yunfeiguo@bioinform2.med.usc.edu"
alias bed2total="perl -e 'print \$ARGV[0],\":\";\$s=0;while(<>){@f=split;\$s+=\$f[2]-\$f[1];};print \$s,\"\\n\"'"
alias dudir="du -d 1 -h | sort -k 1g"
#h does not work on OSX
#alias dudir="du --max-depth=1 -h | sort -k 1h"
alias Rscript="Rscript --vanilla"
alias dh='du -h'
alias ll='ls -l'
alias wl='wc -l'
alias socks='ssh -D 7777 -f -C -q -N t-rex'
alias w0='ssh t-rex'
alias w1='ssh PLS'
alias vd='vimdiff'
alias oc='octave-cli'

#startup scripts
source $HOME/Downloads/git-completion.bash
bind 'set completion-ignore-case on'
ssh-agent
ssh-add
