#!/bin/bash

find . -name '*.py' \
-o -name '*.java' \
-o -iname '*.[ch]' \
-o -name '*.cpp' \
-o -name '*.cc' \
-o -name '*.hpp'  \
> cscope.files

# -b: just build
# -q: create inverted index
cscope -R -b -q
